### PR TITLE
Adds initialization arguments and extracts docstrings

### PR DESCRIPTION
**Pull request by vsu**
Thank you for updating this project for the version 2.0 specification.  

This pull request exposes additional fields in the swagger document in the Api class constructor and also extracts the first line of the docstring from resource methods and schema classes into the appropriate description and summary fields in the document while preserving any content specified explicitly in the doc objects.

### CODE REVIEW

**Comment by swege** [comment]
Thanks for the contribution! I've looked at the changes and it looks good to me - however, I do not currently have time for extended tests, so I merged it and pushed the changes as version 0.26 to PyÜi. Nice to see you have use for the package :)

**Comment by vsu** [comment]
Thanks for updating PyPI.  I'll see if I can work on adding some unit tests.

**Comment by aibati2008** [comment]
@swege can you pls let me know how to import the json file from my own server? It seems loading too slowly from site petstore.swagger.io

image

**Comment by vsu** [comment]
@aibati2008 If you have not changed the default spec path, you can access the JSON from http://localhost:5000/api/swagger.json

**Comment by aibati2008** [comment]
@vsu maybe some misunderstanding.. I mean I can access the JSON but loading slowly (more than 5 seconds) from petstore.swagger.io provide in example. 
When I use flask-restful-swagger, it seems easily to import the JSON and open the page http://localhost:5000/api/swagger.html so fastly.

**Pull request merged**
